### ISSUE TITLE
Issue with npm start

### ISSUE THREAD

**Issue by flyingguitarman** [supercycle91/isomorphic-demo#4]
Cloned the repo and ran 'npm install'. Ran 'npm start' as the readme said. It throws an error though.

```
/Users/danielrehbein/Sites/isomorphic-demo/dist/server.js:638
    return async function (dispatch, getState) {
                 ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isomorphic-demo@1.0.0 start: `webpack --progress --colors --config webpack.config.js && webpack --progress --colors --config webpack.config.server.js && node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isomorphic-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

what am I doing wrong?

**Comment by flyingguitarman** [comment]
didnt realize I was a few node versions back. it works now.
